"""The Python half of the shared behaviour vectors.

``tests/vectors/calendar_grid_v1.json``, ``pairing_code_v1.json`` and
``removal_decision_v1.json`` are generated by
``scripts/generate_behaviour_vectors.py`` and read by this module, by the Swift
``BehaviourVectorTests`` and (pairing code) by the Kotlin
``PairingCodeVectorTest``.  This module proves two things for each file: that
it is exactly what the generator produces today (so nobody hand-edits a vector
to make a client pass), and that it agrees with the real implementation it
claims as its source of truth (so the generator cannot drift from the app).
"""
from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

import pytest

from wattracker.cloud.security import (
    _MAX_PAIRING_INPUT,
    _PAIRING_ALPHABET,
    _PAIRING_FOLD,
    _PAIRING_GROUP,
    _PAIRING_STRIP,
    _PAIRING_SYMBOLS,
    format_pairing_code,
    normalize_pairing_code,
)

ROOT = Path(__file__).resolve().parents[1]
VECTORS = ROOT / "tests" / "vectors"
CLOUD_SESSION_SWIFT = (
    ROOT / "ios" / "WatTracker" / "WatTracker" / "Cloud" / "CloudSession.swift"
)

_SPEC = importlib.util.spec_from_file_location(
    "generate_behaviour_vectors", ROOT / "scripts" / "generate_behaviour_vectors.py"
)
gen = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(gen)


def _load(name: str) -> dict:
    return json.loads((VECTORS / name).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Drift: the committed files are exactly the generator's output.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("path", sorted(gen.OUTPUTS), ids=lambda p: p.name)
def test_vector_file_is_exactly_what_the_generator_writes(path):
    build, ensure_ascii = gen.OUTPUTS[path]
    assert path.read_text(encoding="utf-8") == gen.render(build, ensure_ascii), (
        f"{path.name} is stale or hand-edited; run "
        "python scripts/generate_behaviour_vectors.py"
    )


@pytest.mark.parametrize("path", sorted(gen.OUTPUTS), ids=lambda p: p.name)
def test_vector_file_declares_version_description_and_source(path):
    data = json.loads(path.read_text(encoding="utf-8"))
    assert data["version"] == 1
    assert data["description"]
    assert data["source_of_truth"]
    assert data["generated_by"] == "scripts/generate_behaviour_vectors.py"


# ---------------------------------------------------------------------------
# Calendar grid
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def calendar_vectors() -> dict:
    return _load("calendar_grid_v1.json")


def test_calendar_vectors_cover_the_named_months(calendar_vectors):
    months = {(m["year"], m["month"]): m for m in calendar_vectors["months"]}

    september = months[(2026, 9)]["cells"]
    assert len(september) == 35
    assert september[0]["iso_date"] == "2026-08-31"
    assert september[-1]["iso_date"] == "2026-10-04"

    october = months[(2026, 10)]["cells"]
    assert october[0]["iso_date"] == "2026-09-28"
    assert october[3] == {"iso_date": "2026-10-01", "day": 1, "in_month": True}
    assert october[-1]["iso_date"] == "2026-11-01"

    assert months[(2026, 6)]["cells"][0] == {
        "iso_date": "2026-06-01", "day": 1, "in_month": True,
    }
    assert months[(2026, 5)]["cells"][-1] == {
        "iso_date": "2026-05-31", "day": 31, "in_month": True,
    }
    assert months[(2027, 2)]["rows"] == 4
    assert sum(c["in_month"] for c in months[(2028, 2)]["cells"]) == 29
    assert any(m["rows"] == 6 for m in calendar_vectors["months"])
    assert months[(2026, 12)]["cells"][-1]["iso_date"].startswith("2027-01-")
    assert months[(2027, 1)]["cells"][0]["iso_date"].startswith("2026-12-")


@pytest.fixture()
def client():
    pytest.importorskip("httpx")
    from fastapi.testclient import TestClient

    from wattracker.server import create_app

    with TestClient(create_app()) as value:
        response = value.post(
            "/register",
            data={"username": "rider", "password": "correct horse battery staple"},
            follow_redirects=False,
        )
        assert response.status_code in (302, 303)
        yield value


def test_calendar_vectors_match_the_desktop_grid_builder(client, calendar_vectors):
    # _calendar_data is a closure inside create_app that reads the database,
    # so it is exercised through /api/calendar against the isolated test DB
    # rather than called directly.
    for month in calendar_vectors["months"]:
        response = client.get(
            f"/api/calendar?year={month['year']}&month={month['month']}"
        )
        assert response.status_code == 200
        desktop = [
            {"iso_date": cell["date"], "day": cell["day"], "in_month": cell["in_month"]}
            for week in response.json()["weeks"]
            for cell in week
        ]
        assert desktop == month["cells"], (month["year"], month["month"])
        assert len(response.json()["weeks"]) == month["rows"]


# ---------------------------------------------------------------------------
# Pairing code
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def pairing_vectors() -> dict:
    return _load("pairing_code_v1.json")


def test_pairing_vectors_declare_the_server_constants(pairing_vectors):
    assert pairing_vectors["alphabet"] == _PAIRING_ALPHABET
    assert pairing_vectors["folds"] == dict(_PAIRING_FOLD)
    assert set(pairing_vectors["server_strip"]) == set(_PAIRING_STRIP)
    assert pairing_vectors["symbol_count"] == _PAIRING_SYMBOLS
    assert pairing_vectors["group_size"] == _PAIRING_GROUP
    assert pairing_vectors["max_input_length"] == _MAX_PAIRING_INPUT
    # The client leniency must never overlap what the server already strips,
    # or "client_may_accept" would be describing server behaviour.
    assert not set(pairing_vectors["client_extra_strip"]) & set(_PAIRING_STRIP)


def test_every_pairing_vector_matches_the_server(pairing_vectors):
    for case in pairing_vectors["cases"]:
        value = case["input"]
        assert normalize_pairing_code(value) == case["normalized"], case["name"]
        if case["normalized"] is None:
            assert case["grouped"] is None, case["name"]
            with pytest.raises(ValueError):
                format_pairing_code(value)
        else:
            assert format_pairing_code(value) == case["grouped"], case["name"]


def test_client_leniency_is_only_ever_stripped_line_breaks(pairing_vectors):
    extra = pairing_vectors["client_extra_strip"]
    lenient = [c for c in pairing_vectors["cases"] if c.get("client_may_accept")]
    assert {c["name"] for c in lenient} == {
        "trailing-newline", "trailing-crlf", "embedded-newlines", "embedded-cr",
    }
    for case in lenient:
        assert case["normalized"] is None, case["name"]
        stripped = "".join(c for c in case["input"] if c not in extra)
        assert normalize_pairing_code(stripped) == case["client_normalized"]
        assert format_pairing_code(stripped) == case["client_grouped"]


# ---------------------------------------------------------------------------
# Removal decision
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def removal_vectors() -> dict:
    return _load("removal_decision_v1.json")


def test_removal_tolerance_matches_ios_and_sits_inside_the_server_window(
    removal_vectors,
):
    from wattracker.cloud.api import _MAX_TIMESTAMP

    tolerance = removal_vectors["clock_skew_tolerance_seconds"]
    swift = CLOUD_SESSION_SWIFT.read_text(encoding="utf-8")
    match = re.search(
        r"static let clockSkewTolerance: TimeInterval = (\d+)", swift
    )
    assert match, "CloudSession.clockSkewTolerance not found"
    assert int(match.group(1)) == tolerance
    # The server has no removal rule of its own; the constant it does own is
    # the signed-request timestamp window. The client tolerance is chosen
    # strictly inside it, so a skew the server would refuse a request for is
    # never mistaken for "the server forgot this credential".
    assert removal_vectors["server_timestamp_window_seconds"] == _MAX_TIMESTAMP
    assert 0 < tolerance < _MAX_TIMESTAMP


def test_removal_vectors_cover_the_boundaries(removal_vectors):
    tolerance = removal_vectors["clock_skew_tolerance_seconds"]
    by_offset = {
        (c["status"], c["date_offset_seconds"]): c["complete_locally"]
        for c in removal_vectors["cases"]
    }
    for status in (401, 404):
        assert by_offset[(status, 0)] is True
    assert by_offset[(404, tolerance)] is True
    assert by_offset[(404, -tolerance)] is True
    assert by_offset[(404, tolerance + 1)] is False
    assert by_offset[(404, -(tolerance + 1))] is False
    for status in (429, 503, 500, 502):
        assert by_offset[(status, 0)] is False
    assert by_offset[(None, None)] is False


def test_removal_header_offsets_are_what_the_headers_say(removal_vectors):
    from datetime import datetime, timedelta, timezone

    now = datetime.fromtimestamp(removal_vectors["now_epoch"], tz=timezone.utc)
    for case in removal_vectors["cases"]:
        parsed = gen.parse_imf_fixdate(case["date_header_raw"])
        if case["date_offset_seconds"] is None:
            assert parsed is None, case["name"]
        else:
            assert parsed == now + timedelta(seconds=case["date_offset_seconds"])
