import XCTest

/// The Swift half of the shared behaviour vectors.
///
/// `tests/vectors/calendar_grid_v1.json`, `pairing_code_v1.json` and
/// `removal_decision_v1.json` are generated by
/// `scripts/generate_behaviour_vectors.py` and read, unmodified, by the Python
/// suite (`tests/test_behaviour_vectors.py`), this file, and -- for the pairing
/// code -- the Kotlin `PairingCodeVectorTest`. They are bundled into this test
/// target as resources referenced from the repository, not copied, so the
/// clients are checked against the same rule rather than against two
/// transcriptions of it.
final class BehaviourVectorTests: XCTestCase {
    private func vectors(_ name: String) throws -> [String: Any] {
        let bundle = Bundle(for: type(of: self))
        let url = try XCTUnwrap(
            bundle.url(forResource: name, withExtension: "json"),
            "\(name).json is not in the test bundle. It is referenced from "
                + "tests/vectors/ in the repository root; check the Resources "
                + "build phase of WatTrackerTests."
        )
        let data = try Data(contentsOf: url)
        return try XCTUnwrap(try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func cases(_ file: [String: Any], _ key: String) throws -> [[String: Any]] {
        try XCTUnwrap(file[key] as? [[String: Any]], "missing \(key)")
    }

    /// JSON null arrives as NSNull; this turns it into nil.
    private func optional<T>(_ value: Any?, as type: T.Type) -> T? {
        value as? T
    }

    // MARK: - Calendar grid

    func testCalendarGridMatchesTheDesktopForEveryMonth() throws {
        let file = try vectors("calendar_grid_v1")
        let months = try cases(file, "months")
        XCTAssertFalse(months.isEmpty)
        for entry in months {
            let year = try XCTUnwrap(entry["year"] as? Int)
            let month = try XCTUnwrap(entry["month"] as? Int)
            let expected = try cases(entry, "cells").map { cell in
                CalendarMonth.GridDay(
                    isoDate: try XCTUnwrap(cell["iso_date"] as? String),
                    day: try XCTUnwrap(cell["day"] as? Int),
                    isInMonth: try XCTUnwrap(cell["in_month"] as? Bool)
                )
            }
            XCTAssertEqual(
                CalendarMonth(year: year, month: month).gridDates(), expected,
                String(format: "%04d-%02d", year, month)
            )
        }
    }

    // MARK: - Pairing code

    func testPairingCodeConstantsMatchTheServer() throws {
        let file = try vectors("pairing_code_v1")
        XCTAssertEqual(PairingCode.alphabet, try XCTUnwrap(file["alphabet"] as? String))
        XCTAssertEqual(PairingCode.symbolCount, try XCTUnwrap(file["symbol_count"] as? Int))
        XCTAssertEqual(PairingCode.groupSize, try XCTUnwrap(file["group_size"] as? Int))
        XCTAssertEqual(
            PairingCode.maximumInputLength, try XCTUnwrap(file["max_input_length"] as? Int)
        )
    }

    func testEveryPairingCodeVectorMatches() throws {
        let file = try vectors("pairing_code_v1")
        for entry in try cases(file, "cases") {
            let name = try XCTUnwrap(entry["name"] as? String)
            let input = try XCTUnwrap(entry["input"] as? String)
            let normalized = optional(entry["normalized"], as: String.self)
            let grouped = optional(entry["grouped"], as: String.self)
            let actualNormalized = PairingCode.normalized(input)
            let actualGrouped = PairingCode.grouped(input)
            if entry["client_may_accept"] as? Bool == true {
                // Either refuse like the server, or accept as exactly the
                // stripped code -- never anything else.
                let lenient = try XCTUnwrap(entry["client_normalized"] as? String)
                let lenientGrouped = try XCTUnwrap(entry["client_grouped"] as? String)
                XCTAssertTrue(
                    actualNormalized == nil || actualNormalized == lenient,
                    "\(name): \(String(describing: actualNormalized))"
                )
                XCTAssertTrue(
                    actualGrouped == nil || actualGrouped == lenientGrouped,
                    "\(name): \(String(describing: actualGrouped))"
                )
            } else {
                XCTAssertEqual(actualNormalized, normalized, name)
                XCTAssertEqual(actualGrouped, grouped, name)
            }
        }
    }

    // MARK: - Removal decision

    func testRemovalToleranceMatchesTheVector() throws {
        let file = try vectors("removal_decision_v1")
        XCTAssertEqual(
            CloudSession.clockSkewTolerance,
            TimeInterval(try XCTUnwrap(file["clock_skew_tolerance_seconds"] as? Int))
        )
    }

    func testEveryRemovalDecisionVectorMatches() throws {
        let file = try vectors("removal_decision_v1")
        let now = Date(
            timeIntervalSince1970: TimeInterval(try XCTUnwrap(file["now_epoch"] as? Int))
        )
        for entry in try cases(file, "cases") {
            let name = try XCTUnwrap(entry["name"] as? String)
            let status = optional(entry["status"], as: Int.self)
            let header = optional(entry["date_header_raw"], as: String.self)
            let offset = optional(entry["date_offset_seconds"], as: Int.self)
            let expected = try XCTUnwrap(entry["complete_locally"] as? Bool)

            // The header goes through the same parser the transport uses, so
            // "unparseable means absent" is checked end to end.
            let serverDate = HTTPHeaderDates.date(header)
            if let offset {
                XCTAssertEqual(serverDate, now.addingTimeInterval(TimeInterval(offset)), name)
            } else {
                XCTAssertNil(serverDate, name)
            }
            XCTAssertEqual(
                CloudSession.removalCompletesLocally(
                    status: status, serverDate: serverDate, now: now
                ),
                expected,
                name
            )
        }
    }
}
